name: Integration Tests (Postman)

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Chạy mỗi đêm 2AM

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (for Newman)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d
          sleep 30  # Wait for services to be ready

      - name: Wait for services health check
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000/health; then
              echo "UserService is ready"
              break
            fi
            echo "Waiting for services... ($i/30)"
            sleep 2
          done

      - name: Run Postman collection
        run: |
          # Bạn cần export Postman collection thành file JSON
          # Và commit vào repo tại tests/postman/uitgo-integration.json
          newman run tests/postman/uitgo-integration.json \
            --environment tests/postman/local-env.json \
            --reporters cli,junit \
            --reporter-junit-export test-results/integration-test.xml
        continue-on-error: true

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: test-results/*.xml

      - name: Cleanup
        if: always()
        run: docker-compose down
