name: Run Tests Only

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Cho phép chạy manual

jobs:
  test:
    name: Test All Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install python-jose pydantic python-dotenv
          pip install "passlib[bcrypt]" "bcrypt==4.0.1"

      - name: Run UserService tests
        run: |
          pytest tests/test_userservice.py -v --tb=short
        continue-on-error: false

      - name: Test summary
        if: always()
        run: |
          echo "✅ Tests completed"
